### ISSUE TITLE
win 10 error trying to run WinApp

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#165]
User got this error, when we ran the commands manually:

```
Microsoft Windows [Version 10.0.19044.1586]
(c) Microsoft Corporation. All rights reserved.

C:\Users\roxyp\meshtastic-flasher>venv\Scripts\activate

(venv) C:\Users\roxyp\meshtastic-flasher>pip install meshtastic-flasher
Requirement already satisfied: meshtastic-flasher in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (1.0.99)
Requirement already satisfied: pyserial in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from meshtastic-flasher) (3.5)
Requirement already satisfied: pyside6 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (6.2.3)
Requirement already satisfied: meshtastic>=1.2.92 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (1.2.92)
Requirement already satisfied: geocoder in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (1.38.1)
Requirement already satisfied: psutil in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (5.9.0)
Requirement already satisfied: esptool in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from meshtastic-flasher) (3.2)
Requirement already satisfied: adafruit-nrfutil in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (0.5.3.post16)
Requirement already satisfied: PyGithub in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (1.55)
Requirement already satisfied: qt-material in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic-flasher) (2.10)
Requirement already satisfied: protobuf>=3.13.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (3.19.4)
Requirement already satisfied: pyqrcode>=1.2.1 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (1.2.1)
Requirement already satisfied: pexpect>=4.6.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (4.8.0)
Requirement already satisfied: pyyaml in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (6.0)
Requirement already satisfied: tabulate>=0.8.9 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (0.8.9)
Requirement already satisfied: pypubsub>=4.0.3 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (4.0.3)
Requirement already satisfied: dotmap>=1.3.14 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (1.3.26)
Requirement already satisfied: timeago>=1.0.15 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from meshtastic>=1.2.92->meshtastic-flasher) (1.0.15)
Requirement already satisfied: click>=5.1 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from adafruit-nrfutil->meshtastic-flasher) (8.0.4)
Requirement already satisfied: ecdsa>=0.13 in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from adafruit-nrfutil->meshtastic-flasher) (0.17.0)
Requirement already satisfied: bitstring>=3.1.6 in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from esptool->meshtastic-flasher) (3.1.9)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from esptool->meshtastic-flasher) (36.0.1)
Requirement already satisfied: reedsolo<=1.5.4,>=1.5.3 in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from esptool->meshtastic-flasher) (1.5.4)
Requirement already satisfied: future in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from geocoder->meshtastic-flasher) (0.18.2)
Requirement already satisfied: requests in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from geocoder->meshtastic-flasher) (2.27.1)
Requirement already satisfied: six in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from geocoder->meshtastic-flasher) (1.16.0)
Requirement already satisfied: ratelim in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from geocoder->meshtastic-flasher) (0.1.6)
Requirement already satisfied: pynacl>=1.4.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from PyGithub->meshtastic-flasher) (1.5.0)
Requirement already satisfied: pyjwt>=2.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from PyGithub->meshtastic-flasher) (2.3.0)
Requirement already satisfied: deprecated in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from PyGithub->meshtastic-flasher) (1.2.13)
Requirement already satisfied: shiboken6==6.2.3 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from pyside6->meshtastic-flasher) (6.2.3)
Requirement already satisfied: Jinja2 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from qt-material->meshtastic-flasher) (3.0.3)
Requirement already satisfied: colorama in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from click>=5.1->adafruit-nrfutil->meshtastic-flasher) (0.4.4)
Requirement already satisfied: cffi>=1.12 in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cryptography>=2.1.4->esptool->meshtastic-flasher) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from pexpect>=4.6.0->meshtastic>=1.2.92->meshtastic-flasher) (0.7.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from requests->geocoder->meshtastic-flasher) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from requests->geocoder->meshtastic-flasher) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from requests->geocoder->meshtastic-flasher) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from requests->geocoder->meshtastic-flasher) (2.0.12)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from deprecated->PyGithub->meshtastic-flasher) (1.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from Jinja2->qt-material->meshtastic-flasher) (2.1.1)
Requirement already satisfied: decorator in c:\users\roxyp\meshtastic-flasher\venv\lib\site-packages (from ratelim->geocoder->meshtastic-flasher) (5.1.1)
Requirement already satisfied: pycparser in c:\users\roxyp\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from cffi>=1.12->cryptography>=2.1.4->esptool->meshtastic-flasher) (2.21)

(venv) C:\Users\roxyp\meshtastic-flasher>py --version
Python 3.10.2

(venv) C:\Users\roxyp\meshtastic-flasher>meshtastic-flasher
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\roxyp\meshtastic-flasher\venv\Scripts\meshtastic-flasher.exe\__main__.py", line 4, in <module>
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\meshtastic_flasher\main.py", line 11, in <module>
    import meshtastic_flasher.form
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\meshtastic_flasher\form.py", line 31, in <module>
    from meshtastic_flasher.settings import Settings
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\meshtastic_flasher\settings.py", line 11, in <module>
    from meshtastic_flasher.position_form import PositionForm
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\meshtastic_flasher\position_form.py", line 12, in <module>
    from meshtastic_flasher.util import zero_if_blank
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\meshtastic_flasher\util.py", line 11, in <module>
    from github import Github
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\roxyp\meshtastic-flasher\venv\lib\site-packages\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

(venv) C:\Users\roxyp\meshtastic-flasher>
```

**Comment by mkinney** [comment]
Maybe the user could remove `C:\Users\roxyp\meshtastic-flasher` and re-try? See if they get the same error.
