### ISSUE TITLE
RAK Bootloader upgrade error on Mac

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-gui-installer#180]
Using both the packaged app and PIP I get the following error 

*** found FTHR840BOOT
Bootloader info:
lines:['UF2 Bootloader 0.3.2-109-gd6b28e6-dirty lib/nrfx (v2.0.0) lib/tinyusb (0.6.0-272-g4e6aa0d8) lib/uf2 (heads/master)\n', 'Model: Adafruit Feather nRF52840 Express\n', 'Board-ID: nRF52840-Feather-revD\n', 'SoftDevice: S140 version 6.1.1\n', 'Date: Jun 16 2020\n']
rak bootloader is not current
User confirmed they want to update the RAK bootloader
Checking boot loader version
Upgrading target on /dev/cu.usbmodem11201 with DFU package /Users/garthvanderhouwen/Source/Meshtastic-protobufs/WisCore_RAK4631_Board_Bootloader.zip. Flow control is disabled, Single bank, Touch 1200
Touched serial port /dev/cu.usbmodem11201
Opened serial port /dev/cu.usbmodem11201
Starting DFU upgrade of type 3, SoftDevice size: 151016, bootloader size: 39000, application size: 0
Sending DFU start packet
Sending DFU init packet
Sending firmware file
###############Timed out waiting for acknowledgement from device.

Failed to upgrade target. Error is: No data received on serial port. Not able to proceed.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/__main__.py", line 296, in serial
    dfu.dfu_send_images()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/dfu/dfu.py", line 226, in dfu_send_images
    self._dfu_send_image(HexType.SD_BL, self.manifest.softdevice_bootloader)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/dfu/dfu.py", line 206, in _dfu_send_image
    self.dfu_transport.send_firmware(firmware)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 213, in send_firmware
    self.send_packet(pkt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 243, in send_packet
    ack = self.get_ack_nr()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 282, in get_ack_nr
    raise NordicSemiException("No data received on serial port. Not able to proceed.")
nordicsemi.exceptions.NordicSemiException: No data received on serial port. Not able to proceed.

Possible causes:
- Selected Bootloader version does not match the one on Bluefruit device.
    Please upgrade the Bootloader or select correct version in Tools->Bootloader.
- Baud rate must be 115200, Flow control must be off.
- Target is not in DFU mode. Ground DFU pin and RESET and release both to enter DFU mode.
self.detected_list:['rak4631_5005', 't-echo-1', 'rak4631_5005', 'rak4631_19003']
User picked radio rak4631_5005
self.device_from_picker:rak4631_5005
index:1
end of detect

**Comment by garthvh** [comment]
This worked on Ubuntu with no escalation and on macOS from the pip version using sudo meshtastic-flasher, still getting errors from the packaged MacApp, seems similar to the issues on Windows
