### ISSUE TITLE
No module named 'meshtastic.radioconfig_pb2

### ISSUE THREAD

**Issue by rohanki** [meshtastic/Meshtastic-gui-installer#221]
Apologies if it's a me issue...
I'm trying to run 1.3 Alpha 17. I've got meshtastic-python 1.3 alpha 18 compiled and running fine.
I've installed requirements from requirements.txt and installed meshtastic-flasher with no erros.
When I run meshtastic-flasher I get 

(venv) C:\Users\kingr\meshflash13a17>meshtastic-flasher
Traceback (most recent call last):
  File "C:\Users\kingr\meshflash13a17\venv\Scripts\meshtastic-flasher-script.py", line 33, in <module>
    sys.exit(load_entry_point('meshtastic-flasher==1.3a16', 'console_scripts', 'meshtastic-flasher')())
  File "C:\Users\kingr\meshflash13a17\venv\Scripts\meshtastic-flasher-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\kingr\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\kingr\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kingr\meshflash13a17\venv\lib\site-packages\meshtastic_flasher\main.py", line 11, in <module>
    import meshtastic_flasher.form
  File "C:\Users\kingr\meshflash13a17\venv\lib\site-packages\meshtastic_flasher\form.py", line 32, in <module>
    from meshtastic_flasher.settings import Settings
  File "C:\Users\kingr\meshflash13a17\venv\lib\site-packages\meshtastic_flasher\settings.py", line 11, in <module>
    from meshtastic_flasher.position_form import PositionForm
  File "C:\Users\kingr\meshflash13a17\venv\lib\site-packages\meshtastic_flasher\position_form.py", line 9, in <module>
    import meshtastic.radioconfig_pb2
ModuleNotFoundError: No module named 'meshtastic.radioconfig_pb2'

Having a look in the meshtastic site package, there doesn't seem to be a radioconfig_pb2 file?
it's there in the 1.0 package though.

Again, apologies if I'm missing something!

**Comment by garthvh** [comment]
We have a few features working in the python CLI, the flasher uses the python CLI so we need to get the python CLI working more completely first
