### ISSUE TITLE
error exception

### ISSUE THREAD

**Issue by okiebob** [meshtastic/Meshtastic-gui-installer#227]
Please forgive my ignorance. I'm pretty new to command line interface.  I'm trying to install the meshtastic flashing software.  I've followed all the steps here https://meshtastic.org/docs/getting-started/flashing-firmware/meshtastic-flasher
Python is 3.10.5 
I've tried several times. Sometimes it seems to get further than others. 
Windows 10 pc
I'll copy and paste what it says. Starting with the error below.
It looks to me like the installer is trying to install the following apps 
pyside6
PyGithub
esptool==3.3.1
meshtastic>=1.2.95
qt-material
psutil
adafruit-nrfutil
pytest
pytest-qt
pytest-cov
pylint
geocoder

Would it be helpful to do each one by it's self? I don't know how I would do that.
Thank you

 ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\commands\install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 291, in __init__
    super().__init__(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\network\download.py", line 146, in __call__
    for chunk in chunks:
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 509, in read
    with self._error_catcher():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\lovab\meshtasticflasher\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 446, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2548)

**Comment by garthvh** [comment]
Can't replicate
