### ISSUE TITLE
Add Flatpak support

### ISSUE THREAD

**Issue by Sabering1** [meshtastic/Meshtastic-gui-installer#246]
Publishing this app in a flatpak format would be very beneficial to the whole Linux userbase as a flatpak can be run on any distro.

https://www.flatpak.org/

**Comment by Sabering1** [comment]
So i was trying to build a manifest file, and for dealing with the dependencies and to make it easier i followed the instructions from [https://docs.flatpak.org/en/latest/python.html](url) 

Im using the flatpak-pip-generator to get the dependencies from requrements.txt file and make it a .JSON file

However the script fails at getting shiboken source?

Example of the error

**Traceback (most recent call last):
  File "/home/sabering/git/test/Meshtastic-gui-installer/flatpak-pip-generator", line 259, in <module>
    url = get_tar_package_url_pypi(name, version)
  File "/home/sabering/git/test/Meshtastic-gui-installer/flatpak-pip-generator", line 79, in get_tar_package_url_pypi
    raise Exception(err)
Exception: Failed to get shiboken6-6.4.0 source from https://pypi.org/pypi/shiboken6/6.4.0/json
**


Any ideas?
I can do it the hard way but thats kinda stupid.

**Comment by Sabering1** [comment]
Running the script for individual deps, confirms that this is a pyside6 specific


https://download.qt.io/official_releases/QtForPython/shiboken6/PySide6-6.4.0-src/pyside-setup-opensource-src-6.4.0.zip
