### ISSUE TITLE
meshtastic-flasher not starting

### ISSUE THREAD

**Issue by xor256** [meshtastic/Meshtastic-gui-installer#247]
```
meshtastic-flasher
Traceback (most recent call last):
  File "/home/user/mesh/venv/bin/meshtastic-flasher", line 8, in <module>
    sys.exit(main())
  File "/home/user/mesh/venv/lib64/python3.8/site-packages/meshtastic_flasher/main.py", line 31, in main
    form = meshtastic_flasher.form.Form(lang=lang)
  File "/home/user/mesh/venv/lib64/python3.8/site-packages/meshtastic_flasher/form.py", line 277, in __init__
    self.get_versions_from_disk()
  File "/home/user/mesh/venv/lib64/python3.8/site-packages/meshtastic_flasher/form.py", line 467, in get_versions_from_disk
    self.sort_firmware_versions()
  File "/home/user/mesh/venv/lib64/python3.8/site-packages/meshtastic_flasher/form.py", line 454, in sort_firmware_versions
    curated_versions = [items[0], items[1]]
IndexError: list index out of range
```
 

fedora 

upgrade pip etc.

```
.....
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: timeago, reedsolo, pyserial, pyqrcode, ptyprocess, enum-compat, dotmap, bitstring, wrapt, urllib3, tabulate, six, shiboken6, pyyaml, pypubsub, pyjwt, pygatt, pycparser, psutil, protobuf, pexpect, MarkupSafe, idna, future, decorator, click, charset-normalizer, certifi, requests, ratelim, PySide6-Essentials, meshtastic, Jinja2, ecdsa, deprecated, cffi, qt-material, PySide6-Addons, pynacl, geocoder, cryptography, adafruit-nrfutil, pyside6, PyGithub, esptool, meshtastic-flasher
  DEPRECATION: reedsolo is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for reedsolo ... done
  DEPRECATION: pyqrcode is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyqrcode ... done
  DEPRECATION: pygatt is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pygatt ... done
  DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for future ... done
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyGithub-1.56 PySide6-Addons-6.4.0 PySide6-Essentials-6.4.0 adafruit-nrfutil-0.5.3.post16 bitstring-3.1.9 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 click-8.1.3 cryptography-38.0.1 decorator-5.1.1 deprecated-1.2.13 dotmap-1.3.30 ecdsa-0.18.0 enum-compat-0.0.3 esptool-4.2.1 future-0.18.2 geocoder-1.38.1 idna-3.4 meshtastic-1.3.42 meshtastic-flasher-1.3.30 pexpect-4.8.0 protobuf-4.21.8 psutil-5.9.3 ptyprocess-0.7.0 pycparser-2.21 pygatt-4.0.5 pyjwt-2.6.0 pynacl-1.5.0 pypubsub-4.0.3 pyqrcode-1.2.1 pyserial-3.5 pyside6-6.4.0 pyyaml-6.0 qt-material-2.12 ratelim-0.1.6 reedsolo-1.5.4 requests-2.28.1 shiboken6-6.4.0 six-1.16.0 tabulate-0.9.0 timeago-1.0.16 urllib3-1.26.12 wrapt-1.14.1
```

**Comment by thebentern** [comment]
Upgrading to the latest version. This issue should be resolved.
