### ISSUE TITLE
Can not get versions or connect to device

### ISSUE THREAD

**Issue by boriskogan81** [meshtastic/Meshtastic-gui-installer#269]
I just got a T-Beam and am trying to flash it. 

When I try to get the software versions, I get this:

```
start of get_versions
tag:v2.0.23.7bb281d populate in dropdown?:True
tag:v2.0.22.fbfd0f1 populate in dropdown?:True
Unzipping files now...
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\meshtastic_flasher\form.py", line 435, in on_select_firmware_changed
    meshtastic_flasher.util.unzip_if_necessary(self.firmware_version, zip_file_name)
  File "C:\Program Files\Python310\lib\site-packages\meshtastic_flasher\util.py", line 149, in unzip_if_necessary
    with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
  File "C:\Program Files\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
got versions
```

When I try to detect the device, I get:
````
start of detect
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\meshtastic_flasher\form.py", line 998, in detect
    supported_devices_detected = self.detect_devices()
  File "C:\Program Files\Python310\lib\site-packages\meshtastic_flasher\form.py", line 566, in detect_devices
    supported_devices_detected = meshtastic_flasher.util.wrapped_detect_supported_devices()
  File "C:\Program Files\Python310\lib\site-packages\meshtastic_flasher\util.py", line 42, in wrapped_detect_supported_devices
    return detect_supported_devices()
  File "C:\Program Files\Python310\lib\site-packages\meshtastic\util.py", line 331, in detect_supported_devices
    _, sp_output = subprocess.getstatusoutput('powershell.exe "[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8;'
  File "C:\Program Files\Python310\lib\subprocess.py", line 624, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "C:\Program Files\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Program Files\Python310\lib\subprocess.py", line 1136, in communicate
    stdout = self.stdout.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 265134: character maps to <undefined>
```

I've tried different cables, none works. 

The device powers on and I can connect to it via Bluetooth.

Please help.

**Comment by garthvh** [comment]
Use the web flasher at flasher.meshtastic.org
